### ISSUE TITLE
Include TrackMate overlays when exporting to SVG

### ISSUE THREAD

**Issue by WillGiang** [biovoxxel/BioVoxxel-Figure-Tools#4]
Hi,

My ultimate goal is to export the Tracks overlay (seen on the hyperstack window while hiding the image and excluding spots that aren't included in tracks) into an SVG file. 

Motivation: I used TrackMate on images with small dimensions (e.g. 262 x 76), and using its capture overlay feature (even after adjusting the current zoom of the image window) leads to undesirable results when making figures in InkScape. 

After much confusion, I saw that the TrackMate overlays for [Spots](https://github.com/trackmate-sc/TrackMate/blob/master/src/main/java/fiji/plugin/trackmate/visualization/hyperstack/SpotOverlay.java#L59) and [Tracks](https://github.com/trackmate-sc/TrackMate/blob/master/src/main/java/fiji/plugin/trackmate/visualization/hyperstack/TrackOverlay.java#L54) are made of two classes that extend the `Roi` class.

I'm guessing that this is why TrackMate overlays aren't included when I use the SVG Exporter (and why the usual tricks I was trying to resize the overlays didn't work).

Thanks for a great tool!

**Comment by biovoxxel** [comment]
Thanks for pointing that out. Need to check how to get the coordinates of those ROIs and/or convert them to Point and segmented line ROIs and then it should be possible.

**Comment by biovoxxel** [comment]
This feature will unfortunately not be feasible to integrate, since TrackMates tracks are completely different and would need to be redrawn
